### PR TITLE
Update to Blender 2.83 and above. Fixes #1.

### LINKED ISSUE #1: Not Compatible with Blender 2.83
When using the add-on with Blender 2.83, you get this error:
image

Also A side note, I'd suggest to follow the original blend files custom normal map entirely because the one in this version causes some changes with the quality of the normal map.

### PR DESCRIPTION
**Pull request by mysticfall**

### CODE REVIEW

**Review by theoldben — APPROVED** [review]

**Comment by theoldben** [comment]
Thanks a bunch!

**Comment by mysticfall** [comment]
Thanks! :)

**Comment by mysticfall** [comment]
It appears that you've closed this PR without merging it. I assume it was a mistake since you already approved it?

**Comment by theoldben** [comment]
You are absolutely correct. This is my first contribution by somebody else. From what I have gathered, I need to reopen this task and then merge the pull request into my master branch, is that correct?

**Comment by mysticfall** [comment]
@theoldben Yes, you've done right. Thanks again! :smile:

**Pull request merged**
